name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup msbuild 
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -A Win32 -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --config Release
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: 'build/src/Release/*.dll'
