name: Build

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup msbuild 
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -A Win32 -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --config Release
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: 'build/src/Release/*.dll'

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - name: Download from build
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Publish release
        id: publish
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: |
            *.dll
      - name: Attest Release Files
        id: attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: |
            *.dll
